# Generated by Django 5.1.2 on 2024-11-10 13:11

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Coach',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('experience_years', models.PositiveIntegerField(verbose_name='Годы опыта')),
                ('specialization', models.CharField(max_length=255, verbose_name='Специализация')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='Пользователь')),
            ],
            options={
                'verbose_name': 'Тренер',
                'verbose_name_plural': 'Тренеры',
            },
        ),
        migrations.CreateModel(
            name='Member',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date_of_birth', models.DateField(verbose_name='Дата рождения')),
                ('join_date', models.DateField(verbose_name='Дата вступления')),
                ('belt_color', models.CharField(max_length=50, verbose_name='Цвет пояса')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='Пользователь')),
            ],
            options={
                'verbose_name': 'Участник',
                'verbose_name_plural': 'Участники',
            },
        ),
        migrations.CreateModel(
            name='TrainingSession',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField(verbose_name='Дата')),
                ('time', models.TimeField(verbose_name='Время')),
                ('duration', models.DurationField(verbose_name='Продолжительность')),
                ('max_participants', models.PositiveIntegerField(verbose_name='Максимальное количество участников')),
                ('coach', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='flower_shop.coach', verbose_name='Тренер')),
            ],
            options={
                'verbose_name': 'Тренировка',
                'verbose_name_plural': 'Тренировки',
            },
        ),
        migrations.CreateModel(
            name='TrainingRegistration',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('registration_date', models.DateField(verbose_name='Дата регистрации')),
                ('member', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='flower_shop.member', verbose_name='Участник')),
                ('training_session', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='flower_shop.trainingsession', verbose_name='Тренировка')),
            ],
            options={
                'verbose_name': 'Регистрация на тренировку',
                'verbose_name_plural': 'Регистрации на тренировки',
            },
        ),
    ]
